services:
  db:
    image: pgvector/pgvector:pg15
    container_name: cc_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./cc-backend/.env
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    container_name: cc_redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./cc-backend
    container_name: cc_django_app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload --timeout 120
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    volumes:
      - ./cc-backend:/code
    ports:
      - "8000:8000"
    env_file:
      - ./cc-backend/.env
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_healthy

  frontend:
    build: ./cc-frontend/frontend
    container_name: cc_react_frontend
    volumes:
      - ./cc-frontend/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # Helps with hot reload in Docker
    depends_on:
      - app

  worker:
    build: ./cc-backend
    container_name: cc_celery_worker
    command: celery -A config worker -l info
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    volumes:
      - ./cc-backend:/code
    env_file:
      - ./cc-backend/.env
    depends_on:
      app:
        condition: service_started
      redis:
        condition: service_healthy

  beat:
    build: ./cc-backend
    container_name: cc_celery_beat
    command: celery -A config beat -l info
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    volumes:
      - ./cc-backend:/code
    env_file:
      - ./cc-backend/.env
    depends_on:
      app:
        condition: service_started
      redis:
        condition: service_healthy

volumes:
  postgres_data:
